### ISSUE TITLE
Assemblies and parts cost

### ISSUE THREAD

**Issue by kaare** [ledgersmb/LedgerSMB#2158]
Trying to create an assembly failed for some combinations of parts. The problem seems to be related to missing cost on some parts.

This turned up during a session w/Chris.

**Comment by ehuelsmann** [comment]
@einhverfr , @kaare : do you have a reproduction recipe? Without one, this is pretty hard to solve. Also, this problem may have been solved, because we have a very thorough tester-in-practice who also tested assemblies (@tonka128). He did find issues, mostly with respect to saving/modifying assemblies. From the description, it's unclear if that was the problem here.

**Comment by tonka128** [comment]
Based on my  recent experience I would like to see a recipe as well as this now seems to be workable. I have multiple assemblies made of items without a cost attached. The system will let you create them and sell them but you cant stock them (assemble them) until you have the components stocked (ie it will not let you "assemble" into negative inventory for the components.)

**Comment by ehuelsmann** [comment]
@tonka128 since you can sell them, I'm thinking this isn't a problem in practice, as you can simply wait for the stock components to be either in place or to be corrected through inventory counts, before you restock the assemblies, right?

**Comment by tonka128** [comment]
Actually - I believe there is still an issue (not sure if its the same)
Seems to be related to the "multiple" ways af accounting for inventory.\
If I go and do a "check stock" on my built producst it will tell me how many of each item I can build based on recent stock levels.. if I then try to build them, some items will build, some sill error for "not enough inventory" even though the lsmb check for inventory just said we could... best would be to give you access to a SB and an example to play with - but yes theres still an issue
