### ISSUE TITLE
Action Not Defined: __default when attaching a file

### ISSUE THREAD

**Issue by onno182** [ledgersmb/LedgerSMB#3799]
When attaching a file to a contact (or in any other place) the following error is displayed.

`Action Not Defined: __default`

**Comment by nick-prater** [comment]
Thanks for reporting. What version of LedgerSMB are you using? I've tested in 1.6.4 and can attach files to a contact ok.

**Comment by onno182** [comment]
Thanks for te reply.

My version is the same, 1.6.4.

Maybe it has to do with the setup. Ill recheck the perl dependencies.

Thanks.

**Comment by nick-prater** [comment]
Or we're doing it via a different route. I followed:

* Contacts -> Search
* Find an existing contact
* Click on the `Files` tab
* Click `Attach to Entity`
* Click `Browse` to select a file
* Click `Upload`

**Comment by onno182** [comment]
I followed the exact same procedure.

**Comment by nick-prater** [comment]
A few questions...
What type of file are you trying to attach?
What kind of contact are you trying to attach to? (Vendor, Employee etc...)

Are you able to see what's being submitted by your browser?

In Firefox, right-click somewhere on the page, click `Inspect Element`, click the `Console Tab`.
You should see a POST to `file.pl`.
Expand that line, click the `Params` tab...
Within that, there should be a section `Content-Disposition: form-data; name="action"` with value `attach_file`. Do you see that?

**Comment by onno182** [comment]
The file I am trying to attach is a small PDF file of 486 KB.  I am trying to add it to a vendor, but adding it to an employee (or any other place) gives the same result.

I am using Safari as a web browser.  I also tried with IE on a windows computer, but it yields the same result.

See attached screenshots from the console.

<img width="1303" alt="1" src="https://user-images.githubusercontent.com/13760619/45206399-2ff85b00-b285-11e8-8f54-98a9a794ff6b.png">

<img width="1308" alt="2" src="https://user-images.githubusercontent.com/13760619/45206398-2ff85b00-b285-11e8-89b6-099266d8c357.png">

<img width="2388" alt="3" src="https://user-images.githubusercontent.com/13760619/45206396-2ff85b00-b285-11e8-9653-8182ed23d6b1.png">

When I try access http://boekhouding.skyrise.aero/file.pl, I get the same error message: Action Not Defined: __default

**Comment by onno182** [comment]
If relevant, apache server access log says:

`10.23.0.101 - - [07/Sep/2018:10:23:57 +0200] "GET /contact_reports.pl?action=search&entity_class=&name_part=&control_code=&email=&phone=&contact=&notes=&meta_number=&address=&city=&state=&mail_code=&country=&active_date_from=&active_date_to= HTTP/1.1" 200 8170
10.23.0.101 - - [07/Sep/2018:10:23:58 +0200] "GET /contact.pl?action=get&entity_id=3&meta_number=1 HTTP/1.1" 200 72796
10.23.0.101 - - [07/Sep/2018:10:24:02 +0200] "GET /file.pl?action=show_attachment_screen&ref_key=3&file_class=4&callback=contact.pl%3faction%3dget%26amp%3bentity_class%3d1%26amp%3bentity_id%3d3%26amp%3bcredit_id%3d1 HTTP/1.1" 200 1244
10.23.0.101 - - [07/Sep/2018:10:24:15 +0200] "POST /file.pl HTTP/1.1" 500 98`

**Comment by onno182** [comment]
I have also tried to connect directly to starman (without going through Apache as a proxy, just incase that was causing the trouble).  

Unfortunately it is the same problem.

**Comment by nick-prater** [comment]
Thanks for posting that info. I'm not familiar with Safari. At the end of the last screenshot, it looks like you can expand `Request Data` are you able to do that and post what's there?

@ehuelsmann is looking to install Safari to see if he can replicate the problem. Are you able to test with Firefox or Chrome?

**Comment by onno182** [comment]
This is the request data:

`------WebKitFormBoundarys9CvCbjAe8EMjyUM
Content-Disposition: form-data; name="file_class"

4
------WebKitFormBoundarys9CvCbjAe8EMjyUM
Content-Disposition: form-data; name="ref_key"

1
------WebKitFormBoundarys9CvCbjAe8EMjyUM
Content-Disposition: form-data; name="callback"

contact.pl?action=get&amp;entity_class=&amp;entity_id=1&amp;credit_id=
------WebKitFormBoundarys9CvCbjAe8EMjyUM
Content-Disposition: form-data; name="url"


------WebKitFormBoundarys9CvCbjAe8EMjyUM
Content-Disposition: form-data; name="upload_data"; filename="factuur.pdf"
Content-Type: application/pdf


------WebKitFormBoundarys9CvCbjAe8EMjyUM
Content-Disposition: form-data; name="action"

attach_file
------WebKitFormBoundarys9CvCbjAe8EMjyUM
Content-Disposition: form-data; name="action"

attach_file
------WebKitFormBoundarys9CvCbjAe8EMjyUM--

`

I have installed Firefox, but I get the exact same error:

<img width="2341" alt="5" src="https://user-images.githubusercontent.com/13760619/45212086-4954d380-b294-11e8-82b4-b2a2befe8cd8.png">

**Comment by onno182** [comment]
<img width="2326" alt="6" src="https://user-images.githubusercontent.com/13760619/45212217-9df84e80-b294-11e8-9bf4-ec6274e4a6e6.png">

<img width="2337" alt="7" src="https://user-images.githubusercontent.com/13760619/45212224-a2246c00-b294-11e8-93cc-272a0dbd5ae2.png">

**Comment by ehuelsmann** [comment]
I see the - likely - problem: the 'action' parameter is in the request twice.

**Comment by ehuelsmann** [comment]
In the screenshot you added, I can't see the `[object Object]` bit. But if there's no multipart/form-data with an `action` parameter, that would definitely explain.

**Comment by onno182** [comment]
<img width="2338" alt="untitled" src="https://user-images.githubusercontent.com/13760619/45217385-2c280100-b2a4-11e8-93f5-4d014f195808.png">

**Comment by ehuelsmann** [comment]
ok. that's what I thought, but wanted to see confirmed. This is a problem. The data in the form isn't reaching the server because the client sends `[object Object]` instead of the content of the object.
To debug this, I really need to find myself access to a Safari brawser. (Installing the Windows version of Safari failed miserably due to Apple having pulled that version...)

**Comment by onno182** [comment]
I also tried in Google Chrome, same prob.
<img width="1267" alt="9" src="https://user-images.githubusercontent.com/13760619/45219468-529d6a80-b2ab-11e8-8d94-8b7edb03161b.png">

**Comment by ehuelsmann** [comment]
Thank you for all the information you have provided so far. I can reproduce now on the 1.6.4 Docker images.

**Comment by ehuelsmann** [comment]
Found the problem. Reported the problem upstream. For now, we'll need to work around the breakage by downgrading Dojo.

**Comment by onno182** [comment]
Thanks.

What is the correct method to downgrade?. Is it to replace the Dojo directory with the version 1.13.0?.

Or should I pull a new release?.

**Comment by ehuelsmann** [comment]
I wanted to wait a few days to see what "upstream" (the dojo project) does with our report. When they don't do anything, we'll release a new version based on the old (working) Dojo version 1.13.0. If you need it *now*, then yes, you can simply replace your `UI/js/dojo` directory with Dojo 1.13.0.

**Comment by onno182** [comment]
There is no hurry I can wait.

Just to make sure that it really is the issue,  I ran the following commands in the `UI/js/dojo` directory:

`wget https://github.com/dojo/dojo/archive/1.13.0.tar.gz`
`tar xzf 1.13.0.tar.gz`
`cp -R dojo-1.13.0/* .`

Restarted the server and browser.

However, it is still not working, I get the same problem.  Am I missing something?

**Comment by ehuelsmann** [comment]
possibly, your browser is caching the dojo assets regardless of the browser restart. Sometimes it helps to click the `Reload page` (circular arrow) icon while holding the `Shift` key.

**Comment by onno182** [comment]
I removed the cache, but no change.  I also tried with Firefox, same result.

Ill wait a few days for the new release :).  Thanks.

**Comment by ehuelsmann** [comment]
Upstream indicated that they'll do a new release in the coming week. I'll wait to see what's in that release before deciding which way to go on a new release of our own.

**Comment by ehuelsmann** [comment]
Fixed in the 1.6.5 release.

**Comment by ehuelsmann** [comment]
are you still seeing the same error? (or is the actual error text different now?) Based on the form data that you've provided, I'd expect the submission to work: as far as I can see, there's code to de-duplicate the action. And since both values are the same, it doesn't matter which one gets selected.

**Comment by onno182** [comment]
Correct.  The error is the same, except that it no longer shows [object Object] but the request parameters.

On Firefox and Chrome it is fixed, so the workaround is to not use Safari.  

However, as Safari is quite a popular browser, so it would be nice if it also worked on that.

**Comment by ehuelsmann** [comment]
@onno182 in `lib/LedgerSMB/Middleware/DynamicLoadWorkflow.pm`, there's this line:

```perl
        eval { $req->parameters->get_one('action') } // '__default';
```

Could you replace that line by (the difference being `_one` having been removed):

```perl
        eval { $req->parameters->get('action') } // '__default';
```

And test again with Safari?

We think that should fix your Safari issue. With your confirmation, we can backport the fix and release.

**Comment by onno182** [comment]
Unfortunately the result is the same.  The problem is still there.

**Comment by ehuelsmann** [comment]
If you are still using LedgerSMB 1.6.x, we've released 1.6.13 today with Dojo 1.13.3 (so neither .1 nor .0); could you please provide feedback as to whether the problem still exists?

**Comment by ehuelsmann** [comment]
90 days without feedback. Closing. Feel free to reopen with feedback.
